### ISSUE TITLE
open-variant | error value when a column is not in the file

### ISSUE THREAD

**Issue by FedericaBrando** [bbglab/openvariant#14]
in Open-variant when a file does not contain a field (i.e. STRAND) it returns an error: 

```py
Traceback (most recent call last):
  File "/home/fbrando/miniconda3/envs/openvar_test/bin/openvar", line 8, in <module>
    sys.exit(openvar())
             ^^^^^^^^^
  File "/home/fbrando/miniconda3/envs/openvar_test/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fbrando/miniconda3/envs/openvar_test/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/fbrando/miniconda3/envs/openvar_test/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fbrando/miniconda3/envs/openvar_test/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fbrando/miniconda3/envs/openvar_test/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fbrando/openvariant/openvariant/commands/openvar.py", line 82, in groupby
    for group_key, group_result, command in group_by_task(input_path, annotations, script, key_by=group_by, where=where,
  File "/home/fbrando/openvariant/openvariant/tasks/groupby.py", line 149, in group_by
    selection = _group(base_path, annotation_path, key_by)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fbrando/openvariant/openvariant/tasks/groupby.py", line 42, in _group
    values, result_read = _get_unique_values(file, ann, key_by)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fbrando/openvariant/openvariant/tasks/groupby.py", line 26, in _get_unique_values
    for r in result.read(group_key=key):
  File "/home/fbrando/openvariant/openvariant/variant/variant.py", line 276, in read
    for i, line in enumerate(self._unify(self._path, self._annotation, group_by=group_key)):
  File "/home/fbrando/openvariant/openvariant/variant/variant.py", line 172, in _unify
    for x in self._parser(base_path, annotation, group_by, display_header):
  File "/home/fbrando/openvariant/openvariant/variant/variant.py", line 212, in _parser
    value = value[1].format(**pos)
            ^^^^^^^^^^^^^^^
```

this is because value is ` value = ({}, None)` when the file does not have a column with the related field.

**Comment by FedericaBrando** [comment]
```diff
   elif type_ann == AnnotationTypes.INTERNAL.name:
                            if len(value[0]) == 1:
                                pos = list(value[0].values())[0]
                                value = line[pos] if value is not None else None
+                           elif len(value[0]) == 0:
+                               value = line[pos] if value[1] is not None else None 
                            else:
                                pos = {}
                                for val, position in value[0].items():
                                    pos.update({val: line[position]})
                                value = value[1].format(**pos)
```
