### ISSUE TITLE
Error: module 're' has no attribute 'Pattern' 

### ISSUE THREAD

**Issue by dmartmillan** [bbglab/openvariant#20]
Hello,

I did a simple script with OpenVariant to check some benchmark but I got the following error just importing some classes of package:
```
Traceback (most recent call last):
  File "read.py", line 4, in <module>
    from openvariant import Annotation, Variant
  File "/home/david/anaconda3/envs/openvar-bench/lib/python3.6/site-packages/openvariant/__init__.py", line 3, in <module>
    from openvariant.annotation.annotation import Annotation
  File "/home/david/anaconda3/envs/openvar-bench/lib/python3.6/site-packages/openvariant/annotation/annotation.py", line 12, in <module>
    from openvariant.annotation.builder import AnnotationTypesBuilders
  File "/home/david/anaconda3/envs/openvar-bench/lib/python3.6/site-packages/openvariant/annotation/builder.py", line 45, in <module>
    DirnameBuilder = Tuple[str, Builder, re.Pattern]
AttributeError: module 're' has no attribute 'Pattern'
```
It seems that the error comes from the `re` package, there's no `Pattern` attribute.
It will be nice if you can replicate the error in your computers. Let see if you have the same error, if so, we will need to check how can we replace the typing. (e.g. instead of using re.Pattern, typing it as str, it will work... but I'm not sure). 

I let the script and the annotation file:

```
import sys
from os import getcwd
from os.path import dirname
from openvariant import Annotation, Variant

dataset_file = sys.argv[1]
annotation_file = './annotation.yaml'

annotation = Annotation(annotation_path=annotation_file)
result = Variant(path=dataset_file, annotation=annotation)

li = []

for line in result.read():
    try:
        li.append(line["AN"])
    except KeyError:
        continue

print(f"{(sum(li) / len(li)):.2f}")
```
```
pattern:
  - '*.vcf.gz'
recursive: false

annotation:
  - type: 'internal'
    field: 'AN'
    fieldSource:
      - 'AN'
  ```
 
 And the file to read it is the following one:

```
 wget -O - http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_raw_GT_with_annot/20201028_CCDG_14151_B01_GRM_WGS_2020-08-05_chr1.recalibrated_variants.vcf.gz \
    | zcat - \
    | head -30000  > 1kg.chr1.subset.vcf

gzip -c 1kg.chr1.subset.vcf > 1kg.chr1.subset.vcf.gz
```

That comes from the following repository:
https://github.com/brentp/vcf-bench

Thank you in advance.

**Comment by dmartmillan** [comment]
Yes, it was that. I was working with `Python 3.6.13`, and with it worked with `Python 3.9.18`. 
It the documentation appears that OpenVariant requires `Python 3.9 or higher` but in the README only appears `Python 3 or higher`, we should change that. 

Thanks @FedericaBrando
